package smarthomesimulator.presentation;

public enum Permission {
    USERS_READ,
    USERS_CREATE,
    USERS_UPDATE,
    USERS_DELETE,

    DEVICES_READ,
    DEVICES_CREATE,
    DEVICES_UPDATE,
    DEVICES_DELETE,
    DEVICES_TOGGLE,

    ROOMS_READ,
    ROOMS_CREATE,
    ROOMS_UPDATE,
    ROOMS_DELETE,

    SCENES_READ,
    SCENES_CREATE,
    SCENES_UPDATE,
    SCENES_DELETE,
    SCENES_ACTIVATE,

    TRIGGERS_READ,
    TRIGGERS_CREATE,
    TRIGGERS_UPDATE,
    TRIGGERS_DELETE,

    ENERGYLOGS_READ,
    ENERGYLOGS_CREATE,
    ENERGYLOGS_UPDATE,
    ENERGYLOGS_DELETE,

    DOCUMENTS_EXPORT
}
